version: '2.1'

services:
  db:
    image: mysql
    healthcheck:
      test: exit 0
    ports:
     -  5432:3306
    environment:
      - MYSQL_DATABASE=onlyairmen
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
        - ./spring/src/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
