version: '2.1'

services:
  db:
    image: mysql
    healthcheck:
      test: exit 0
    ports:
     -  3306:3306
    environment:
      - MYSQL_DATABASE=onlyairmen
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
        - ./spring/src/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth:
    image: agadient2018/ajgrepo:proj2_auth
    depends_on:
      db:
        condition: service_healthy
    links:
     - db
    ports:
     - 8084:8080


  chat:
    image: btanusi/only-airmen-chat-server:latest 
    depends_on:
      db:
       condition: service_healthy
    links:
     - db
    ports:
     - 8080:8080

  profiles:
    image: violinalan/user-profile-spring-boot-docker
    depends_on:
      db:
        condition: service_healthy
    links:
     - db
    ports:
     - 8082:8080

  search:
    image: jrconsole/only-airmen-search-server
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
     - 8081:8080
    
  only-airmen-react:
      image: violinalan/only-airmen-react
      command: npm start
      depends_on:
        - db
        - auth
        - chat
        - profiles
        - search
      ports:
        - 3000:3000
